apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: worker-deployment
  name: worker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: worker-deployment
    spec:
      containers:
      - image: dockersamples/examplevotingapp_worker
        name: examplevotingapp-worker-sflr7
        resources: {}
status: {}
